// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package cache_service

import (
	"context"
	"fmt"
)

type BaseResp struct {
	Code int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int64) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}
func (p *BaseResp) SetCode(val int64) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "msg",
}

type CacheItem struct {
	Key         string `thrift:"key,1" frugal:"1,default,string" json:"key"`
	Data        string `thrift:"data,2" frugal:"2,default,string" json:"data"`
	LifeSpan    int64  `thrift:"life_span,3" frugal:"3,default,i64" json:"life_span"`
	CreatedOn   int64  `thrift:"created_on,4" frugal:"4,default,i64" json:"created_on"`
	AccessedOn  int64  `thrift:"accessed_on,5" frugal:"5,default,i64" json:"accessed_on"`
	AccessCount int64  `thrift:"access_count,6" frugal:"6,default,i64" json:"access_count"`
}

func NewCacheItem() *CacheItem {
	return &CacheItem{}
}

func (p *CacheItem) InitDefault() {
}

func (p *CacheItem) GetKey() (v string) {
	return p.Key
}

func (p *CacheItem) GetData() (v string) {
	return p.Data
}

func (p *CacheItem) GetLifeSpan() (v int64) {
	return p.LifeSpan
}

func (p *CacheItem) GetCreatedOn() (v int64) {
	return p.CreatedOn
}

func (p *CacheItem) GetAccessedOn() (v int64) {
	return p.AccessedOn
}

func (p *CacheItem) GetAccessCount() (v int64) {
	return p.AccessCount
}
func (p *CacheItem) SetKey(val string) {
	p.Key = val
}
func (p *CacheItem) SetData(val string) {
	p.Data = val
}
func (p *CacheItem) SetLifeSpan(val int64) {
	p.LifeSpan = val
}
func (p *CacheItem) SetCreatedOn(val int64) {
	p.CreatedOn = val
}
func (p *CacheItem) SetAccessedOn(val int64) {
	p.AccessedOn = val
}
func (p *CacheItem) SetAccessCount(val int64) {
	p.AccessCount = val
}

func (p *CacheItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheItem(%+v)", *p)
}

var fieldIDToName_CacheItem = map[int16]string{
	1: "key",
	2: "data",
	3: "life_span",
	4: "created_on",
	5: "accessed_on",
	6: "access_count",
}

type NewCacheRequest_ struct {
	Name string `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
}

func NewNewCacheRequest_() *NewCacheRequest_ {
	return &NewCacheRequest_{}
}

func (p *NewCacheRequest_) InitDefault() {
}

func (p *NewCacheRequest_) GetName() (v string) {
	return p.Name
}
func (p *NewCacheRequest_) SetName(val string) {
	p.Name = val
}

func (p *NewCacheRequest_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NewCacheRequest_(%+v)", *p)
}

var fieldIDToName_NewCacheRequest_ = map[int16]string{
	1: "name",
}

type NewCacheResponse_ struct {
	Success bool      `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Base    *BaseResp `thrift:"base,2" frugal:"2,default,BaseResp" json:"base"`
}

func NewNewCacheResponse_() *NewCacheResponse_ {
	return &NewCacheResponse_{}
}

func (p *NewCacheResponse_) InitDefault() {
}

func (p *NewCacheResponse_) GetSuccess() (v bool) {
	return p.Success
}

var NewCacheResponse__Base_DEFAULT *BaseResp

func (p *NewCacheResponse_) GetBase() (v *BaseResp) {
	if !p.IsSetBase() {
		return NewCacheResponse__Base_DEFAULT
	}
	return p.Base
}
func (p *NewCacheResponse_) SetSuccess(val bool) {
	p.Success = val
}
func (p *NewCacheResponse_) SetBase(val *BaseResp) {
	p.Base = val
}

func (p *NewCacheResponse_) IsSetBase() bool {
	return p.Base != nil
}

func (p *NewCacheResponse_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NewCacheResponse_(%+v)", *p)
}

var fieldIDToName_NewCacheResponse_ = map[int16]string{
	1: "success",
	2: "base",
}

type SetRequest struct {
	Cache    string `thrift:"cache,1,required" frugal:"1,required,string" json:"cache"`
	Key      string `thrift:"key,2,required" frugal:"2,required,string" json:"key"`
	Value    string `thrift:"value,3,required" frugal:"3,required,string" json:"value"`
	LifeSpan *int64 `thrift:"life_span,4,optional" frugal:"4,optional,i64" json:"life_span,omitempty"`
}

func NewSetRequest() *SetRequest {
	return &SetRequest{}
}

func (p *SetRequest) InitDefault() {
}

func (p *SetRequest) GetCache() (v string) {
	return p.Cache
}

func (p *SetRequest) GetKey() (v string) {
	return p.Key
}

func (p *SetRequest) GetValue() (v string) {
	return p.Value
}

var SetRequest_LifeSpan_DEFAULT int64

func (p *SetRequest) GetLifeSpan() (v int64) {
	if !p.IsSetLifeSpan() {
		return SetRequest_LifeSpan_DEFAULT
	}
	return *p.LifeSpan
}
func (p *SetRequest) SetCache(val string) {
	p.Cache = val
}
func (p *SetRequest) SetKey(val string) {
	p.Key = val
}
func (p *SetRequest) SetValue(val string) {
	p.Value = val
}
func (p *SetRequest) SetLifeSpan(val *int64) {
	p.LifeSpan = val
}

func (p *SetRequest) IsSetLifeSpan() bool {
	return p.LifeSpan != nil
}

func (p *SetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetRequest(%+v)", *p)
}

var fieldIDToName_SetRequest = map[int16]string{
	1: "cache",
	2: "key",
	3: "value",
	4: "life_span",
}

type SetResponse struct {
	Base *BaseResp `thrift:"base,1" frugal:"1,default,BaseResp" json:"base"`
}

func NewSetResponse() *SetResponse {
	return &SetResponse{}
}

func (p *SetResponse) InitDefault() {
}

var SetResponse_Base_DEFAULT *BaseResp

func (p *SetResponse) GetBase() (v *BaseResp) {
	if !p.IsSetBase() {
		return SetResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *SetResponse) SetBase(val *BaseResp) {
	p.Base = val
}

func (p *SetResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *SetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetResponse(%+v)", *p)
}

var fieldIDToName_SetResponse = map[int16]string{
	1: "base",
}

type GetRequest struct {
	Cache string `thrift:"cache,1,required" frugal:"1,required,string" json:"cache"`
	Key   string `thrift:"key,2,required" frugal:"2,required,string" json:"key"`
}

func NewGetRequest() *GetRequest {
	return &GetRequest{}
}

func (p *GetRequest) InitDefault() {
}

func (p *GetRequest) GetCache() (v string) {
	return p.Cache
}

func (p *GetRequest) GetKey() (v string) {
	return p.Key
}
func (p *GetRequest) SetCache(val string) {
	p.Cache = val
}
func (p *GetRequest) SetKey(val string) {
	p.Key = val
}

func (p *GetRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetRequest(%+v)", *p)
}

var fieldIDToName_GetRequest = map[int16]string{
	1: "cache",
	2: "key",
}

type GetResponse struct {
	Value string    `thrift:"value,1,required" frugal:"1,required,string" json:"value"`
	Base  *BaseResp `thrift:"base,2" frugal:"2,default,BaseResp" json:"base"`
}

func NewGetResponse() *GetResponse {
	return &GetResponse{}
}

func (p *GetResponse) InitDefault() {
}

func (p *GetResponse) GetValue() (v string) {
	return p.Value
}

var GetResponse_Base_DEFAULT *BaseResp

func (p *GetResponse) GetBase() (v *BaseResp) {
	if !p.IsSetBase() {
		return GetResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetResponse) SetValue(val string) {
	p.Value = val
}
func (p *GetResponse) SetBase(val *BaseResp) {
	p.Base = val
}

func (p *GetResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetResponse(%+v)", *p)
}

var fieldIDToName_GetResponse = map[int16]string{
	1: "value",
	2: "base",
}

type DeleteRequest struct {
	Cache string `thrift:"cache,1,required" frugal:"1,required,string" json:"cache"`
	Key   string `thrift:"key,2,required" frugal:"2,required,string" json:"key"`
}

func NewDeleteRequest() *DeleteRequest {
	return &DeleteRequest{}
}

func (p *DeleteRequest) InitDefault() {
}

func (p *DeleteRequest) GetCache() (v string) {
	return p.Cache
}

func (p *DeleteRequest) GetKey() (v string) {
	return p.Key
}
func (p *DeleteRequest) SetCache(val string) {
	p.Cache = val
}
func (p *DeleteRequest) SetKey(val string) {
	p.Key = val
}

func (p *DeleteRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteRequest(%+v)", *p)
}

var fieldIDToName_DeleteRequest = map[int16]string{
	1: "cache",
	2: "key",
}

type DeleteResponse struct {
	Deleted bool      `thrift:"deleted,1" frugal:"1,default,bool" json:"deleted"`
	Base    *BaseResp `thrift:"base,2" frugal:"2,default,BaseResp" json:"base"`
}

func NewDeleteResponse() *DeleteResponse {
	return &DeleteResponse{}
}

func (p *DeleteResponse) InitDefault() {
}

func (p *DeleteResponse) GetDeleted() (v bool) {
	return p.Deleted
}

var DeleteResponse_Base_DEFAULT *BaseResp

func (p *DeleteResponse) GetBase() (v *BaseResp) {
	if !p.IsSetBase() {
		return DeleteResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteResponse) SetDeleted(val bool) {
	p.Deleted = val
}
func (p *DeleteResponse) SetBase(val *BaseResp) {
	p.Base = val
}

func (p *DeleteResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteResponse(%+v)", *p)
}

var fieldIDToName_DeleteResponse = map[int16]string{
	1: "deleted",
	2: "base",
}

type ExistsRequest struct {
	Cache string `thrift:"cache,1,required" frugal:"1,required,string" json:"cache"`
	Key   string `thrift:"key,2,required" frugal:"2,required,string" json:"key"`
}

func NewExistsRequest() *ExistsRequest {
	return &ExistsRequest{}
}

func (p *ExistsRequest) InitDefault() {
}

func (p *ExistsRequest) GetCache() (v string) {
	return p.Cache
}

func (p *ExistsRequest) GetKey() (v string) {
	return p.Key
}
func (p *ExistsRequest) SetCache(val string) {
	p.Cache = val
}
func (p *ExistsRequest) SetKey(val string) {
	p.Key = val
}

func (p *ExistsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExistsRequest(%+v)", *p)
}

var fieldIDToName_ExistsRequest = map[int16]string{
	1: "cache",
	2: "key",
}

type ExistsResponse struct {
	Exists bool      `thrift:"exists,1" frugal:"1,default,bool" json:"exists"`
	Base   *BaseResp `thrift:"base,2" frugal:"2,default,BaseResp" json:"base"`
}

func NewExistsResponse() *ExistsResponse {
	return &ExistsResponse{}
}

func (p *ExistsResponse) InitDefault() {
}

func (p *ExistsResponse) GetExists() (v bool) {
	return p.Exists
}

var ExistsResponse_Base_DEFAULT *BaseResp

func (p *ExistsResponse) GetBase() (v *BaseResp) {
	if !p.IsSetBase() {
		return ExistsResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ExistsResponse) SetExists(val bool) {
	p.Exists = val
}
func (p *ExistsResponse) SetBase(val *BaseResp) {
	p.Base = val
}

func (p *ExistsResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ExistsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ExistsResponse(%+v)", *p)
}

var fieldIDToName_ExistsResponse = map[int16]string{
	1: "exists",
	2: "base",
}

type CacheService interface {
	New_(ctx context.Context, req *NewCacheRequest_) (r *NewCacheResponse_, err error)

	Get(ctx context.Context, req *GetRequest) (r *GetResponse, err error)

	Set(ctx context.Context, req *SetRequest) (r *SetResponse, err error)

	Delete(ctx context.Context, req *DeleteRequest) (r *DeleteResponse, err error)

	Exists(ctx context.Context, req *ExistsRequest) (r *ExistsResponse, err error)
}

type CacheServiceNewArgs struct {
	Req *NewCacheRequest_ `thrift:"req,1" frugal:"1,default,NewCacheRequest_" json:"req"`
}

func NewCacheServiceNewArgs() *CacheServiceNewArgs {
	return &CacheServiceNewArgs{}
}

func (p *CacheServiceNewArgs) InitDefault() {
}

var CacheServiceNewArgs_Req_DEFAULT *NewCacheRequest_

func (p *CacheServiceNewArgs) GetReq() (v *NewCacheRequest_) {
	if !p.IsSetReq() {
		return CacheServiceNewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CacheServiceNewArgs) SetReq(val *NewCacheRequest_) {
	p.Req = val
}

func (p *CacheServiceNewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CacheServiceNewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceNewArgs(%+v)", *p)
}

var fieldIDToName_CacheServiceNewArgs = map[int16]string{
	1: "req",
}

type CacheServiceNewResult struct {
	Success *NewCacheResponse_ `thrift:"success,0,optional" frugal:"0,optional,NewCacheResponse_" json:"success,omitempty"`
}

func NewCacheServiceNewResult() *CacheServiceNewResult {
	return &CacheServiceNewResult{}
}

func (p *CacheServiceNewResult) InitDefault() {
}

var CacheServiceNewResult_Success_DEFAULT *NewCacheResponse_

func (p *CacheServiceNewResult) GetSuccess() (v *NewCacheResponse_) {
	if !p.IsSetSuccess() {
		return CacheServiceNewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CacheServiceNewResult) SetSuccess(x interface{}) {
	p.Success = x.(*NewCacheResponse_)
}

func (p *CacheServiceNewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CacheServiceNewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceNewResult(%+v)", *p)
}

var fieldIDToName_CacheServiceNewResult = map[int16]string{
	0: "success",
}

type CacheServiceGetArgs struct {
	Req *GetRequest `thrift:"req,1" frugal:"1,default,GetRequest" json:"req"`
}

func NewCacheServiceGetArgs() *CacheServiceGetArgs {
	return &CacheServiceGetArgs{}
}

func (p *CacheServiceGetArgs) InitDefault() {
}

var CacheServiceGetArgs_Req_DEFAULT *GetRequest

func (p *CacheServiceGetArgs) GetReq() (v *GetRequest) {
	if !p.IsSetReq() {
		return CacheServiceGetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CacheServiceGetArgs) SetReq(val *GetRequest) {
	p.Req = val
}

func (p *CacheServiceGetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CacheServiceGetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceGetArgs(%+v)", *p)
}

var fieldIDToName_CacheServiceGetArgs = map[int16]string{
	1: "req",
}

type CacheServiceGetResult struct {
	Success *GetResponse `thrift:"success,0,optional" frugal:"0,optional,GetResponse" json:"success,omitempty"`
}

func NewCacheServiceGetResult() *CacheServiceGetResult {
	return &CacheServiceGetResult{}
}

func (p *CacheServiceGetResult) InitDefault() {
}

var CacheServiceGetResult_Success_DEFAULT *GetResponse

func (p *CacheServiceGetResult) GetSuccess() (v *GetResponse) {
	if !p.IsSetSuccess() {
		return CacheServiceGetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CacheServiceGetResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetResponse)
}

func (p *CacheServiceGetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CacheServiceGetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceGetResult(%+v)", *p)
}

var fieldIDToName_CacheServiceGetResult = map[int16]string{
	0: "success",
}

type CacheServiceSetArgs struct {
	Req *SetRequest `thrift:"req,1" frugal:"1,default,SetRequest" json:"req"`
}

func NewCacheServiceSetArgs() *CacheServiceSetArgs {
	return &CacheServiceSetArgs{}
}

func (p *CacheServiceSetArgs) InitDefault() {
}

var CacheServiceSetArgs_Req_DEFAULT *SetRequest

func (p *CacheServiceSetArgs) GetReq() (v *SetRequest) {
	if !p.IsSetReq() {
		return CacheServiceSetArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CacheServiceSetArgs) SetReq(val *SetRequest) {
	p.Req = val
}

func (p *CacheServiceSetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CacheServiceSetArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceSetArgs(%+v)", *p)
}

var fieldIDToName_CacheServiceSetArgs = map[int16]string{
	1: "req",
}

type CacheServiceSetResult struct {
	Success *SetResponse `thrift:"success,0,optional" frugal:"0,optional,SetResponse" json:"success,omitempty"`
}

func NewCacheServiceSetResult() *CacheServiceSetResult {
	return &CacheServiceSetResult{}
}

func (p *CacheServiceSetResult) InitDefault() {
}

var CacheServiceSetResult_Success_DEFAULT *SetResponse

func (p *CacheServiceSetResult) GetSuccess() (v *SetResponse) {
	if !p.IsSetSuccess() {
		return CacheServiceSetResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CacheServiceSetResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetResponse)
}

func (p *CacheServiceSetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CacheServiceSetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceSetResult(%+v)", *p)
}

var fieldIDToName_CacheServiceSetResult = map[int16]string{
	0: "success",
}

type CacheServiceDeleteArgs struct {
	Req *DeleteRequest `thrift:"req,1" frugal:"1,default,DeleteRequest" json:"req"`
}

func NewCacheServiceDeleteArgs() *CacheServiceDeleteArgs {
	return &CacheServiceDeleteArgs{}
}

func (p *CacheServiceDeleteArgs) InitDefault() {
}

var CacheServiceDeleteArgs_Req_DEFAULT *DeleteRequest

func (p *CacheServiceDeleteArgs) GetReq() (v *DeleteRequest) {
	if !p.IsSetReq() {
		return CacheServiceDeleteArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CacheServiceDeleteArgs) SetReq(val *DeleteRequest) {
	p.Req = val
}

func (p *CacheServiceDeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CacheServiceDeleteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceDeleteArgs(%+v)", *p)
}

var fieldIDToName_CacheServiceDeleteArgs = map[int16]string{
	1: "req",
}

type CacheServiceDeleteResult struct {
	Success *DeleteResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteResponse" json:"success,omitempty"`
}

func NewCacheServiceDeleteResult() *CacheServiceDeleteResult {
	return &CacheServiceDeleteResult{}
}

func (p *CacheServiceDeleteResult) InitDefault() {
}

var CacheServiceDeleteResult_Success_DEFAULT *DeleteResponse

func (p *CacheServiceDeleteResult) GetSuccess() (v *DeleteResponse) {
	if !p.IsSetSuccess() {
		return CacheServiceDeleteResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CacheServiceDeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteResponse)
}

func (p *CacheServiceDeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CacheServiceDeleteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceDeleteResult(%+v)", *p)
}

var fieldIDToName_CacheServiceDeleteResult = map[int16]string{
	0: "success",
}

type CacheServiceExistsArgs struct {
	Req *ExistsRequest `thrift:"req,1" frugal:"1,default,ExistsRequest" json:"req"`
}

func NewCacheServiceExistsArgs() *CacheServiceExistsArgs {
	return &CacheServiceExistsArgs{}
}

func (p *CacheServiceExistsArgs) InitDefault() {
}

var CacheServiceExistsArgs_Req_DEFAULT *ExistsRequest

func (p *CacheServiceExistsArgs) GetReq() (v *ExistsRequest) {
	if !p.IsSetReq() {
		return CacheServiceExistsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CacheServiceExistsArgs) SetReq(val *ExistsRequest) {
	p.Req = val
}

func (p *CacheServiceExistsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CacheServiceExistsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceExistsArgs(%+v)", *p)
}

var fieldIDToName_CacheServiceExistsArgs = map[int16]string{
	1: "req",
}

type CacheServiceExistsResult struct {
	Success *ExistsResponse `thrift:"success,0,optional" frugal:"0,optional,ExistsResponse" json:"success,omitempty"`
}

func NewCacheServiceExistsResult() *CacheServiceExistsResult {
	return &CacheServiceExistsResult{}
}

func (p *CacheServiceExistsResult) InitDefault() {
}

var CacheServiceExistsResult_Success_DEFAULT *ExistsResponse

func (p *CacheServiceExistsResult) GetSuccess() (v *ExistsResponse) {
	if !p.IsSetSuccess() {
		return CacheServiceExistsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CacheServiceExistsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ExistsResponse)
}

func (p *CacheServiceExistsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CacheServiceExistsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CacheServiceExistsResult(%+v)", *p)
}

var fieldIDToName_CacheServiceExistsResult = map[int16]string{
	0: "success",
}
