// Code generated by Kitex v0.16.1. DO NOT EDIT.

package cacheservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	cache_service "github.com/coco1660/cache2go/internal/controller/rpc/idl/kitex_gen/cache_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"New": kitex.NewMethodInfo(
		new_Handler,
		newCacheServiceNewArgs,
		newCacheServiceNewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Get": kitex.NewMethodInfo(
		getHandler,
		newCacheServiceGetArgs,
		newCacheServiceGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Set": kitex.NewMethodInfo(
		setHandler,
		newCacheServiceSetArgs,
		newCacheServiceSetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newCacheServiceDeleteArgs,
		newCacheServiceDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Exists": kitex.NewMethodInfo(
		existsHandler,
		newCacheServiceExistsArgs,
		newCacheServiceExistsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	cacheServiceServiceInfo                = NewServiceInfo()
	cacheServiceServiceInfoForClient       = NewServiceInfoForClient()
	cacheServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cacheServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cacheServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cacheServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CacheService"
	handlerType := (*cache_service.CacheService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "cache_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func new_Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cache_service.CacheServiceNewArgs)
	realResult := result.(*cache_service.CacheServiceNewResult)
	success, err := handler.(cache_service.CacheService).New_(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCacheServiceNewArgs() interface{} {
	return cache_service.NewCacheServiceNewArgs()
}

func newCacheServiceNewResult() interface{} {
	return cache_service.NewCacheServiceNewResult()
}

func getHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cache_service.CacheServiceGetArgs)
	realResult := result.(*cache_service.CacheServiceGetResult)
	success, err := handler.(cache_service.CacheService).Get(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCacheServiceGetArgs() interface{} {
	return cache_service.NewCacheServiceGetArgs()
}

func newCacheServiceGetResult() interface{} {
	return cache_service.NewCacheServiceGetResult()
}

func setHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cache_service.CacheServiceSetArgs)
	realResult := result.(*cache_service.CacheServiceSetResult)
	success, err := handler.(cache_service.CacheService).Set(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCacheServiceSetArgs() interface{} {
	return cache_service.NewCacheServiceSetArgs()
}

func newCacheServiceSetResult() interface{} {
	return cache_service.NewCacheServiceSetResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cache_service.CacheServiceDeleteArgs)
	realResult := result.(*cache_service.CacheServiceDeleteResult)
	success, err := handler.(cache_service.CacheService).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCacheServiceDeleteArgs() interface{} {
	return cache_service.NewCacheServiceDeleteArgs()
}

func newCacheServiceDeleteResult() interface{} {
	return cache_service.NewCacheServiceDeleteResult()
}

func existsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*cache_service.CacheServiceExistsArgs)
	realResult := result.(*cache_service.CacheServiceExistsResult)
	success, err := handler.(cache_service.CacheService).Exists(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCacheServiceExistsArgs() interface{} {
	return cache_service.NewCacheServiceExistsArgs()
}

func newCacheServiceExistsResult() interface{} {
	return cache_service.NewCacheServiceExistsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) New_(ctx context.Context, req *cache_service.NewCacheRequest_) (r *cache_service.NewCacheResponse_, err error) {
	var _args cache_service.CacheServiceNewArgs
	_args.Req = req
	var _result cache_service.CacheServiceNewResult
	if err = p.c.Call(ctx, "New", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Get(ctx context.Context, req *cache_service.GetRequest) (r *cache_service.GetResponse, err error) {
	var _args cache_service.CacheServiceGetArgs
	_args.Req = req
	var _result cache_service.CacheServiceGetResult
	if err = p.c.Call(ctx, "Get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Set(ctx context.Context, req *cache_service.SetRequest) (r *cache_service.SetResponse, err error) {
	var _args cache_service.CacheServiceSetArgs
	_args.Req = req
	var _result cache_service.CacheServiceSetResult
	if err = p.c.Call(ctx, "Set", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *cache_service.DeleteRequest) (r *cache_service.DeleteResponse, err error) {
	var _args cache_service.CacheServiceDeleteArgs
	_args.Req = req
	var _result cache_service.CacheServiceDeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Exists(ctx context.Context, req *cache_service.ExistsRequest) (r *cache_service.ExistsResponse, err error) {
	var _args cache_service.CacheServiceExistsArgs
	_args.Req = req
	var _result cache_service.CacheServiceExistsResult
	if err = p.c.Call(ctx, "Exists", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
