// Code generated by Kitex v0.16.1. DO NOT EDIT.

package cacheservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	cache_service "github.com/coco1660/cache2go/internal/controller/rpc/idl/kitex_gen/cache_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	New_(ctx context.Context, req *cache_service.NewCacheRequest_, callOptions ...callopt.Option) (r *cache_service.NewCacheResponse_, err error)
	Get(ctx context.Context, req *cache_service.GetRequest, callOptions ...callopt.Option) (r *cache_service.GetResponse, err error)
	Set(ctx context.Context, req *cache_service.SetRequest, callOptions ...callopt.Option) (r *cache_service.SetResponse, err error)
	Delete(ctx context.Context, req *cache_service.DeleteRequest, callOptions ...callopt.Option) (r *cache_service.DeleteResponse, err error)
	Exists(ctx context.Context, req *cache_service.ExistsRequest, callOptions ...callopt.Option) (r *cache_service.ExistsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCacheServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCacheServiceClient struct {
	*kClient
}

func (p *kCacheServiceClient) New_(ctx context.Context, req *cache_service.NewCacheRequest_, callOptions ...callopt.Option) (r *cache_service.NewCacheResponse_, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.New_(ctx, req)
}

func (p *kCacheServiceClient) Get(ctx context.Context, req *cache_service.GetRequest, callOptions ...callopt.Option) (r *cache_service.GetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Get(ctx, req)
}

func (p *kCacheServiceClient) Set(ctx context.Context, req *cache_service.SetRequest, callOptions ...callopt.Option) (r *cache_service.SetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Set(ctx, req)
}

func (p *kCacheServiceClient) Delete(ctx context.Context, req *cache_service.DeleteRequest, callOptions ...callopt.Option) (r *cache_service.DeleteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, req)
}

func (p *kCacheServiceClient) Exists(ctx context.Context, req *cache_service.ExistsRequest, callOptions ...callopt.Option) (r *cache_service.ExistsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Exists(ctx, req)
}
