// Code generated by Kitex v0.16.1. DO NOT EDIT.
package cacheservice

import (
	server "github.com/cloudwego/kitex/server"
	cache_service "github.com/coco1660/cache2go/internal/controller/rpc/idl/kitex_gen/cache_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler cache_service.CacheService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler cache_service.CacheService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
